
name = "trr-canvas"
main = "worker/worker.ts"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
preview_urls = true

[observability]
enabled = true

[vars]
VITE_TLDRAW_LICENSE_KEY = ""

[assets]
not_found_handling = "single-page-application"
directory = "./dist/client"

# Set up the durable object used for each tldraw room
[durable_objects]
bindings = [
    { name = "TLDRAW_DURABLE_OBJECT", class_name = "TldrawDurableObject" },
]

# Updated migration for free plan - use SQLite-based Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["TldrawDurableObject"]

# We store rooms and asset uploads in an R2 bucket
[[r2_buckets]]
binding = 'TLDRAW_BUCKET'
bucket_name = 'trr-canvas-bucket'
preview_bucket_name = 'trr-canvas-bucket-preview'
